//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cowrie_Categories
    {
        public Cowrie_Categories()
        {
            this.Cowrie_Products = new HashSet<Cowrie_Products>();
        }
    
        public int Id { get; set; }
        public int PortalId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Cowrie_Products> Cowrie_Products { get; set; }
    }
}
